Repository GavinF17/git-jock, pull requests merged in 2020-10, with the labels that each got.

#4 2 Added pull from list
  jockcli/git.py
  jockcli/jockcli.py
Labels: enhancement

#10 8 add unit tests
  jockcli/git.py
  jockcli/jockcli.py
  requirements.txt
  tests/__init__.py
  tests/unit/__init__.py
  tests/unit/test_git.py
  tests/unit/test_jockcli.py
  tests/unit/test_utils.py
Labels: enhancement

#12 9 add GitHub actions
  .actrc
  .github/workflows/verify.yml
  jockcli/git.py
  jockcli/utils.py
  tests/unit/test_git.py
  tests/unit/test_jockcli.py
Labels: ci/cd, quality

#17 16 Updated action to run on PRs
  .github/workflows/verify.yml
Labels: bug

#14 5 Fetch multiple repositories
  jockcli/git.py
  jockcli/jockcli.py
  tests/unit/test_git.py
  tests/unit/test_jockcli.py
Labels: enhancement, hacktoberfest-accepted

#20 19 Added 3.9
  .github/workflows/verify.yml
Labels: ci/cd, quality

#71 #69 fix build that 6 broke
  .actevents/pr_labeled.json
  .actevents/push_alpha.json
  .actevents/push_normal.json
  .github/workflows/verify.yml
  jock/cli.py
  tests/unit/test_jockcli.py
Labels: hacktoberfest-accepted
